# where the daemon will serve queries from
port: 8090

# adding a line to 'consumers' implies that carbonsearch should use this consumer.
# the value should be the absolute path to the config file for that consumer type
consumers:
    kafka: "kafka.yaml"
    httpapi: "httpapi.yaml"
